### ISSUE TITLE
Separate `onnxruntime-gpu` version in `conda`

### ISSUE THREAD

**Issue by valentynbez** [conda-forge/onnxruntime-feedstock#103]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I work with `onnxruntime` app on a cluster, which gives a super speedup for model inference. Yet, our server doesn't have GPUs, but nodes do have. On the other hand, nodes don't have an internet connection. 
This prevents `conda` from installing GPU version of `onnxruntime` and I need to search for a workaround to enforce CUDA installation via `conda` recipe. Would there be a possibility to enforce a CUDA installation via `conda` recipe? 

### Installed packages

```shell
Not relevant.
```

### Environment info

```shell
Not relevant.
```

**Comment by traversaro** [comment]
Perhaps you may find useful to set CONDA_OVERRIDE_CUDA to the cuda version you want to support?

**Comment by valentynbez** [comment]
Thank you a lot for the tip, I couldn't find the solution and it solves my problem!
