### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by comatrion** [conda-forge/onnxruntime-feedstock#31]
### Comment:

Would it be possible to have a windows build for this feedstock?

**Comment by xhochy** [comment]
Have a look at the failing PR.

**Comment by comatrion** [comment]
Ah I see https://github.com/conda-forge/onnxruntime-feedstock/pull/10

But the build logs seem to have been deleted. 

Is it worth trying onnxruntime v1.11.0?

**Comment by cbourjau** [comment]
Closed with #56
